package mp.evilhangman

fun main() {
    val evilHangman = EvilHangman()
    val newGame = evilHangman.newGame()
    println(newGame)
    println()
    println(evilHangman.guess('a'))
    println()
    println(evilHangman.guess('a'))
    println()
    println(evilHangman.guess('b'))
    println()
    println(evilHangman.guess('c'))
    println()
    println(evilHangman.guess('e'))
    println()
    println(evilHangman.guess('m'))
    println()
    println(evilHangman.guess('n'))
    println()
    println(evilHangman.guess('d'))
    println()
    println(evilHangman.guess('m'))
    println()
    println(evilHangman.guess('i'))
    println()
    println(evilHangman.guess('o'))
    println()
    println(evilHangman.guess('u'))
    println()
    println(evilHangman.guess('g'))
    println()
    println(evilHangman.guess('s'))
    println()
    println(evilHangman.guess('t'))
    println()
    println(evilHangman.guess('r'))
    println()
    println(evilHangman.guess('l'))
    println()
    println(evilHangman.guess('h'))
    println()
    println(evilHangman.guess('y'))
    println()
    println(evilHangman.guess('f'))
    println()
    println(evilHangman.guess('w'))
    println()
    println(evilHangman.guess('x'))
    println()
}